<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCT4Mdxu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCT4Mdxu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCT4Mdxu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCT4Mdxu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCT4Mdxu\App_KernelDevDebugContainer([
    'container.build_hash' => 'CT4Mdxu',
    'container.build_id' => '58e0b64a',
    'container.build_time' => 1712918460,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCT4Mdxu');
