<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMKB3Wft\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMKB3Wft/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMKB3Wft.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMKB3Wft\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMKB3Wft\App_KernelDevDebugContainer([
    'container.build_hash' => 'MKB3Wft',
    'container.build_id' => '91b65779',
    'container.build_time' => 1713086534,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMKB3Wft');
