<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMrgo05a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMrgo05a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMrgo05a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMrgo05a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMrgo05a\App_KernelDevDebugContainer([
    'container.build_hash' => 'Mrgo05a',
    'container.build_id' => 'a970447e',
    'container.build_time' => 1712999383,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMrgo05a');
